name: Check Bitcoin Nodes Releases

on:
  workflow_dispatch:
  schedule:
    - cron: "20 23 * * *"  # Runs every day at 23:20 UTC
    - cron: "20 11 * * *"  # Runs every day at 11:20 UTC
jobs:
  bitcoin-core:
    uses: ./.github/workflows/check-release-template.yml
    with:
      item-id: bitcoin-core
      item-type: bitcoin-nodes
      github-org: bitcoin
      github-repo: bitcoin
      latestRelease: true
      social-enabled: true
  bitcoin-knots:
    uses: ./.github/workflows/check-release-template.yml
    with:
      item-id: bitcoin-knots
      item-type: bitcoin-nodes
      github-org: bitcoinknots
      github-repo: bitcoin
      latestRelease: true
      social-enabled: true
  citadel:
    uses: ./.github/workflows/check-release-template.yml
    with:
      item-id: citadel
      item-type: bitcoin-nodes
      gitlabProjectId: "48888641"
      tag: true
      social-enabled: true
  minibolt:
    uses: ./.github/workflows/check-release-template.yml
    with:
      item-id: minibolt
      item-type: bitcoin-nodes
      github-org: minibolt-guide
      github-repo: minibolt
      latestRelease: true
      social-enabled: true
  mynode-community-edition:
    uses: ./.github/workflows/check-release-template.yml
    with:
      item-id: mynode-community-edition
      item-type: bitcoin-nodes
      changelog-url: https://raw.githubusercontent.com/mynodebtc/mynode/master/CHANGELOG
      social-enabled: true
  mynode-model-one:
    uses: ./.github/workflows/check-release-template.yml
    with:
      item-id: mynode-model-one
      item-type: bitcoin-nodes
      changelog-url: https://raw.githubusercontent.com/mynodebtc/mynode/master/CHANGELOG
  mynode-model-two:
    uses: ./.github/workflows/check-release-template.yml
    with:
      item-id: mynode-model-two
      item-type: bitcoin-nodes
      changelog-url: https://raw.githubusercontent.com/mynodebtc/mynode/master/CHANGELOG
  mynode-premium:
    uses: ./.github/workflows/check-release-template.yml
    with:
      item-id: mynode-premium
      item-type: bitcoin-nodes
      changelog-url: https://raw.githubusercontent.com/mynodebtc/mynode/master/CHANGELOG
  nodl-one-mark-2:
    uses: ./.github/workflows/check-release-template.yml
    with:
      item-id: nodl-one-mark-2
      item-type: bitcoin-nodes
      changelog-url: https://gitlab.lightning-solutions.eu/nodl-private/nodl-admin-private/-/raw/nodl-one/www/changelog.txt?ref_type=heads
      social-enabled: true
  nodl-two:
    uses: ./.github/workflows/check-release-template.yml
    with:
      item-id: nodl-two
      item-type: bitcoin-nodes
      changelog-url: https://gitlab.lightning-solutions.eu/nodl-private/nodl-admin-private/-/raw/nodl-two/www/changelog.txt?ref_type=heads
  parmanode:
    uses: ./.github/workflows/check-release-template.yml
    with:
      item-id: parmanode
      item-type: bitcoin-nodes
      changelog-url: https://raw.githubusercontent.com/ArmanTheParman/Parmanode/refs/heads/master/changelog.txt
      social-enabled: true
  raspiblitz:
    uses: ./.github/workflows/check-release-template.yml
    with:
      item-id: raspiblitz
      item-type: bitcoin-nodes
      github-org: raspiblitz
      github-repo: raspiblitz
      latestRelease: true
      social-enabled: true
  raspibolt:
    uses: ./.github/workflows/check-release-template.yml
    with:
      item-id: raspibolt
      item-type: bitcoin-nodes
      github-org: raspibolt
      github-repo: raspibolt
      latestRelease: true
      social-enabled: true
  start9-diy:
    uses: ./.github/workflows/check-release-template.yml
    with:
      item-id: start9-diy
      item-type: bitcoin-nodes
      github-org: Start9Labs
      github-repo: start-os
      latestRelease: true
      social-enabled: true
  start9-server-one:
    uses: ./.github/workflows/check-release-template.yml
    with:
      item-id: start9-server-one
      item-type: bitcoin-nodes
      github-org: Start9Labs
      github-repo: start-os
      latestRelease: true
  start9-server-pure:
    uses: ./.github/workflows/check-release-template.yml
    with:
      item-id: start9-server-pure
      item-type: bitcoin-nodes
      github-org: Start9Labs
      github-repo: start-os
      latestRelease: true
  umbrel-diy:
    uses: ./.github/workflows/check-release-template.yml
    with:
      item-id: umbrel-diy
      item-type: bitcoin-nodes
      github-org: getumbrel
      github-repo: umbrel
      allReleases: true
      allReleasesInclude: "umbrel"
      social-enabled: true
  umbrel-home:
    uses: ./.github/workflows/check-release-template.yml
    with:
      item-id: umbrel-home
      item-type: bitcoin-nodes
      github-org: getumbrel
      github-repo: umbrel
      allReleases: true
      allReleasesInclude: "umbrel"
  
