name: Update Releases

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3,9,15,21 * * *"  # Runs every six hours

jobs:
  update-releases:
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install
      working-directory: scripts

    - name: Update release
      id: fetch-release-step
      working-directory: scripts
      run: node update-releases.js

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7.0.6
      id: create-pull-request
      with:
        title: "New releases"
        commit-message: "New releases"
        branch: "new-releases"
        add-paths: "item-types/*/items/*.json,releases.md"
        reviewers: "${{ env.ASSIGNEE }}"

    - name: Trigger Automerge Workflow
      run: |
        curl -X POST -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/${{ github.repository }}/actions/workflows/build.yml/dispatches \
        -d '{"ref":"new-releases"}'